### ISSUE TITLE
Heeeelp!

### ISSUE THREAD

**Issue by rasadeyan** [jmazouri/TelegramBotSharp#1]
After writing the key in the apikey.txt and starting the project
I see this Error on this line inthe Main method of examlpe

Console.WriteLine("Hi, i'm {0}! ID: {1}", bot.Me.FirstName, bot.Me.Id);

error:
Object reference not set to an instance of an object.

can you help me to solve it !?

**Comment by jmazouri** [comment]
Do you have RestSharp referenced? You can install it through Nuget.

**Comment by rasadeyan** [comment]
Yeap! i have installed it! but i still have problem !?

**Comment by jmazouri** [comment]
I just pushed an update - try pulling the newest changes. Also, if you're compiling from source, try the nuget package here: https://www.nuget.org/packages/TelegramBotSharp/

**Comment by rasadeyan** [comment]
Thanks! my VS had some problems! but i figured them out!

It works!
Thanks alot

**Comment by isarjanfaza** [comment]
hi
when add https://www.nuget.org/packages/TelegramBotSharp/ in project show this error:

Install-Package TelegramBotSharp
Attempting to resolve dependency 'RestSharp (≥ 105.1.0)'.
Installing 'RestSharp 105.1.0'.
Successfully installed 'RestSharp 105.1.0'.
Installing 'TelegramBotSharp 0.0.6.0'.
Successfully installed 'TelegramBotSharp 0.0.6.0'.
Removing 'RestSharp 105.0.0' from TelegramBotSharp.ConsoleExample.
Successfully removed 'RestSharp 105.0.0' from TelegramBotSharp.ConsoleExample.
Adding 'RestSharp 105.1.0' to TelegramBotSharp.ConsoleExample.
Successfully added 'RestSharp 105.1.0' to TelegramBotSharp.ConsoleExample.
Adding 'TelegramBotSharp 0.0.6.0' to TelegramBotSharp.ConsoleExample.
Uninstalling 'TelegramBotSharp 0.0.6.0'.
Successfully uninstalled 'TelegramBotSharp 0.0.6.0'.
Uninstalling 'RestSharp 105.1.0'.
Successfully uninstalled 'RestSharp 105.1.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'TelegramBotSharp 0.0.6.0'. You are trying to install this package into a project 
that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package TelegramBotSharp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
PM> 


why?

**Comment by rasadeyan** [comment]
u need to use .net 4.5.2
