### ISSUE TITLE
Getting User ID by phoneNumber

### ISSUE THREAD

**Issue by rasadeyan** [jmazouri/TelegramBotSharp#2]
How can I get userID by phone number !?

**Comment by jmazouri** [comment]
Unfortunately I don't believe the API has that functionality yet. They are still actively working on adding more endpoints, though, as far as I'm aware.

**Comment by rasadeyan** [comment]
Thanks! it is very imortant for me!!!

jusy as a question! do you know any well implemented telegram API for C# !? not telegram Bot API!

**Comment by jmazouri** [comment]
I don't think anyone has come close to implementing one yet, sorry. I've been looking for one for a while now as well!

**Comment by rasadeyan** [comment]
thanks!
