### ISSUE TITLE
Please help me ?

### ISSUE THREAD

**Issue by isarjanfaza** [jmazouri/TelegramBotSharp#3]
hi
when add https://www.nuget.org/packages/TelegramBotSharp/ in project show this error:

Install-Package TelegramBotSharp
Attempting to resolve dependency 'RestSharp (≥ 105.1.0)'.
Installing 'RestSharp 105.1.0'.
Successfully installed 'RestSharp 105.1.0'.
Installing 'TelegramBotSharp 0.0.6.0'.
Successfully installed 'TelegramBotSharp 0.0.6.0'.
Removing 'RestSharp 105.0.0' from TelegramBotSharp.ConsoleExample.
Successfully removed 'RestSharp 105.0.0' from TelegramBotSharp.ConsoleExample.
Adding 'RestSharp 105.1.0' to TelegramBotSharp.ConsoleExample.
Successfully added 'RestSharp 105.1.0' to TelegramBotSharp.ConsoleExample.
Adding 'TelegramBotSharp 0.0.6.0' to TelegramBotSharp.ConsoleExample.
Uninstalling 'TelegramBotSharp 0.0.6.0'.
Successfully uninstalled 'TelegramBotSharp 0.0.6.0'.
Uninstalling 'RestSharp 105.1.0'.
Successfully uninstalled 'RestSharp 105.1.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'TelegramBotSharp 0.0.6.0'. You are trying to install this package into a project 
that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.
At line:1 char:1

Install-Package TelegramBotSharp
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [Install-Package], InvalidOperationException
FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
PM>

why?

**Comment by jmazouri** [comment]
The library is precompiled for .NET v4.5.2, please change your project's target framework to that or download and compile the library yourself.

**Comment by isarjanfaza** [comment]
hi
but installed framwork 4.5.2 in my computer and freamwork project in 4.5?
but , show this error?

**Comment by jmazouri** [comment]
Try following the steps under the section "Changing the target version" here:
https://msdn.microsoft.com/en-us/library/bb398202.aspx
